title: Flipping the Coins, Rolling the Dice
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Creating a Coin Flipper
  - title: Making the Die
  - title: Building A Basic Interface
  - title: Advanced Interface: Functions and Manipulations
  - title: "Challenge: Improve the User Experience"
    challenge: true