title: Weather Dashboard
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Exploring Weather Data
  - title: Creating a Weather Dashboard
  - title: Creating a Function
  - title: "Challenge: Cloud Deploy"
    challenge: true