title: fruit-machine
hero_image: images/banner.png
description: fruit-machine description
version: 4
listed: false
copyedit: false
last_tested: "2018-12-14"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
